### ISSUE TITLE
Crashes occur when trying to print non-English characters or view them in the watcher.

### ISSUE THREAD

**Issue by rkxhs02** [godotengine/godot-vscode-plugin#524]
### Godot version

4.13 stable

### VS Code version

1.84.0

### Godot Tools VS Code extension version

1.3.1

### System information

window 10

### Issue description

In Godot 4.0, while debugging, if you print a language other than English or if a string variable contains characters from a non-English language, the game instance crashes and terminates.

### Steps to reproduce

print("한글")

**Comment by DaelonSuzuka** [comment]
This seems to already work correctly using the upcoming `1.4.0` version of the Extension. There are a lot of improvements to the debugger in general, so it's possible I fixed this by accident. It's also possible that the problem is with Godot `4.1.3`, and has been fixed in the version of `4.2beta3` that I'm running in this screenshot.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/eee048f8-d63d-4c8a-b6b3-377f1da1f9a1)

![Code_qMEqHUrdrf](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/f48b05a6-11f5-4f66-9013-bee93a2d7b9c)

**Comment by DaelonSuzuka** [comment]
The majority of the debugger changes aren't in `master`, they're in #452.

**Comment by DaelonSuzuka** [comment]
The debugger changes from #452 have been merged into `master` by now. I suspect that the original issue here was caused by the old debugger writing the game's stdout to an output channel instead of the debug console where it belongs.

The new debugger sends prints to the correct system, which can correctly handle all the unicode I've tested it with. 

This bug should be fixed in the next release.

**Comment by Kolgolar** [comment]
I have build the plugin from the current master branch, but the game instance still crashes right before printing non-English characters

**Comment by DaelonSuzuka** [comment]
@Kolgolar Do you plan to _share_ the non-English characters you're trying to print, so I can try to reproduce your issue?

**Comment by Kolgolar** [comment]
@DaelonSuzuka, yep, for example:
`print("Тест")`

**Comment by DaelonSuzuka** [comment]
Looks right to me:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/7205baf2-701d-47c3-b0af-a5a7352feb31)

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/493fa05b-8981-4b0e-a519-00ee60ed6eec)

> I have built the plugin from the current master branch

Did you build the plugin, and then install the resulting `.vsix` file?

**Comment by Kolgolar** [comment]
@DaelonSuzuka Turns out, I forgot to recreate my `launch.json` file. Now everything works just fine, thank you for the help!

**Comment by DaelonSuzuka** [comment]
Awesome! I'm glad there wasn't actually a problem.
